# Copyright 2023 Canonical Ltd.
# See LICENSE file for licensing details.

"""Set up IP address changes manager."""

import logging
import os
import signal
import subprocess
import typing

from ops.framework import Object
from ops.model import ActiveStatus

logger = logging.getLogger(__name__)

# File path for the spawned IP address manager process to write logs.
LOG_FILE_PATH = "/var/log/ip_address_manager.log"


if typing.TYPE_CHECKING:
    from charm import MySQLOperatorCharm


class IPAddressManager(Object):
    """Manages changes in the unit's IP address.

    Dispatches a custom event every 30s to update hostnames in the charm container.
    """

    def __init__(self, charm: "MySQLOperatorCharm"):
        super().__init__(charm, "ip-address-manager")

        self.charm = charm

    def start_observer(self):
        """Start the IP address observer running in a new process."""
        if not isinstance(self.charm.unit.status, ActiveStatus) or self.charm.peers is None:
            return

        if "ip-address-manager-pid" in self.charm.unit_peer_data:
            pid = int(self.charm.unit_peer_data["ip-address-manager-pid"])
            try:
                os.kill(pid, 0)
                return
            except OSError:
                pass

        logger.info("Starting IP address manager process")

        # We need to trick Juju into thinking that we are not running
        # in a hook context, as Juju will disallow use of juju-run.
        new_env = os.environ.copy()
        if "JUJU_CONTEXT_ID" in new_env:
            new_env.pop("JUJU_CONTEXT_ID")

        # Input generated by the charm
        process = subprocess.Popen(  # noqa:S603
            [
                "/usr/bin/python3",
                "scripts/ip_address_dispatcher.py",
                "/usr/bin/juju-exec",
                self.charm.unit.name,
                self.charm.charm_dir,
            ],
            # Cannot use a context
            stdout=open(LOG_FILE_PATH, "a"),  # noqa: SIM115
            stderr=subprocess.STDOUT,
            env=new_env,
        )

        self.charm.unit_peer_data.update({"ip-address-manager-pid": f"{process.pid}"})
        logging.info(f"Started IP address manager process with PID {process.pid}")

    def stop_observer(self):
        """Stop running the observer if it is indeed running."""
        if self.charm.peers is None or "ip-address-manager-pid" not in self.charm.unit_peer_data:
            return

        observer_pid = int(self.charm.unit_peer_data["ip-address-manager-pid"])

        try:
            os.kill(observer_pid, signal.SIGTERM)
            logger.info(f"Stopped running IP address manager process with PID {observer_pid}")
            del self.charm.unit_peer_data["ip-address-manager-pid"]
        except OSError:
            pass
