# Copyright 2021 Canonical Ltd.
# See LICENSE file for licensing details.

options:
  cluster-name:
    description: Optional - Name of the MySQL InnoDB cluster, set once at deployment
    type: string
  cluster-set-name:
    description: |
      Optional - Name for async replication cluster set, set once at deployment.
      On `recreate-clster` action call, the cluster set name will be re-generated automatically.
    type: string
  profile:
    description: |
      profile representing the scope of deployment, and used to be able to enable high-level
      customisation of sysconfigs, resource checks/allocation, warning levels, etc.
      Allowed values are: “production” and “testing”.
    type: string
    default: production
  profile-limit-memory:
    type: int
    description: |
      Amount of memory in Megabytes to limit MySQL and associated process to.
      If unset, this will be decided according to the default memory limit in the selected profile.
      Only comes into effect when the `production` profile is selected.
  plugin-audit-enabled:
    description: Enable the audit plugin
    type: boolean
    default: true
  plugin-audit-strategy:
    description: |
      Audit log plugin strategy. Allowed values are: "semi-async" and "async".
      Ref. at https://docs.percona.com/percona-server/8.4/audit-log-plugin.html#audit_log_strategy
    type: string
    default: async
  binlog-retention-days:
    description: Number of days for binary logs retention
    type: int
    default: 7
  logs-audit-policy:
    description: |
      Audit log policy. Allowed values are: "all", "logins" (default), "queries".
      Ref. at https://docs.percona.com/percona-server/8.4/audit-log-plugin.html#audit_log_policy
    type: string
    default: logins
  logs-retention-period:
    description: |
      Specifies the retention period for rotated logs, in days. Accepts an integer value of 3 or
      greater, or the special value "auto". When set to "auto" (default), the retention period is
      3 days, except when COS-related, where it is 1 day
    type: string
    default: auto
  pause-after-unit-refresh:
    description: |
      Wait for manual confirmation to resume refresh after these units refresh
      Allowed values: "all", "first", "none"
    type: string
    default: first
  tls-client-private-key:
    type: secret
    description: |
      A Juju secret URI of a secret containing the private key for client-to-server TLS certificates.
      The private key must be PEM formatted, base64 encoded and at least 2048 bits long.
  tls-peer-private-key:
    type: secret
    description: |
      A Juju secret URI of a secret containing the private key for peer-to-peer TLS certificates.
      The private key must be PEM formatted, base64 encoded and at least 2048 bits long.
  # Experimental features
  experimental-max-connections:
    type: int
    description: |
      Maximum number of connections allowed to the MySQL server.
      When set max-connections value take precedence over the memory utilizations
      againts innodb_buffer_pool_size.
      This is an experimental feature and may be removed in future releases.
