# Copyright 2026 Canonical Ltd.
# See LICENSE file for licensing details.

charm_major = 1
workload = "8.4"

charm = "8.4/1.0.0" # TODO remove

[snap]
name = "charmed-mysql"

[snap.revisions]
x86_64 = "186"
aarch64 = "185"
s390x = "187"
