# Copyright 2026 Canonical Ltd.
# See LICENSE file for licensing details.

charm_major = 1
workload = "8.4"

[snap]
name = "charmed-mysql"

[snap.revisions]
x86_64 = "219"  # https://github.com/canonical/charmed-mysql-snap/pull/104
aarch64 = "212"
s390x = "210"
