# Copyright 2026 Canonical Ltd.
# See LICENSE file for licensing details.

charm_major = 1
workload = "8.4"

[snap]
name = "charmed-mysql"

[snap.revisions]
x86_64 = "200"
aarch64 = "198"
s390x = "199"
