juju:
  model-defaults:
    logging-config: <root>=INFO; unit=DEBUG
  extra-bootstrap-args: --debug --keep-broken --agent-version 2.9.57
providers:
  microk8s:
    enable: true
    bootstrap: true
    addons:
      - dns
      - hostpath-storage
host:
  snaps:
    jhack:
      channel: latest/edge
      connections:
        - jhack:dot-local-share-juju snapd
