# Copyright 2026 Canonical Ltd.
# See LICENSE file for licensing details.

[dependency-groups]
build = [
    "charm-refresh-build-version~=0.4.0"
]
format = [
    "ruff~=0.16",
]
lint = [
    "codespell~=2.4",
    "ruff~=0.16",
]
test = [
    "allure-pytest~=2.13",
    "allure-pytest-default-results~=0.1.2",
    "boto3~=1.28",
    "cryptography~=50.0",
    "jinja2~=3.1",
    "jubilant~=1.4.0",
    "juju~=3.6",
    "lightkube~=0.19.0",
    "mysql-connector-python~=9.1.0",
    "pytest~=9.0",
    "pyyaml~=6.0",
    "tenacity~=8.2",
    "urllib3~=2.0",
    "tomli~=2.3",
    "tomli-w~=1.2",
]

# Packaging tools configuration
[tool.poetry]
package-mode = false
requires-poetry = ">=2.2.0"

[tool.poetry.dependencies]
python = "^3.12"
# The following dependencies have been copied from the single-kernel
# kubernetes extra section, given charmcraftlocal lack of support
# for the extra section.
lightkube = { version = "^0.19" }
single-kernel-mysql = { path = "../common", develop = true }

[tool.poetry.group.build]
optional = true

[tool.poetry.group.format]
optional = true

[tool.poetry.group.lint]
optional = true

[tool.poetry.group.test]
optional = true

# Linting tools configuration
[tool.ruff]
preview = true
line-length = 100
target-version = "py312"
src = ["src"]

[tool.ruff.lint]
explicit-preview-rules = true
select = [
    "A",      # Enable flake8-builtins
    "C",      # Enable mccabe
    "D",      # Enable pydocstyle
    "E",      # Enable pycodestyle errors
    "W",      # Enable pycodestyle warnings
    "F",      # Enable pyflakes
    "I",      # Enable isort
    "N",      # Enable PEP8 naming
    "S608",   # Enable flake8-bandit query injection
    "CPY001", # Enable copyright notice check
]
ignore = [
    "A001",   # Ignore A001 Variable shadowing a Python builtin
    "D100",   # Ignore D100 Missing docstring in public module
    "D104",   # Ignore D104 Missing docstring in __init__
    "E731",   # Ignore E731 Do not assign a `lambda` expression
    "F541",   # Ignore F541 F-strings without and placeholders
]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = [
    "F401",   # Ignore F401 Imported but unused
    "F403",   # Ignore F403 Unable to detect undefined names
]
"tests/*" = [
    "S",      # Disable security checks
    "D1",     # Disable docstring checks
    "E501",   # Disable line-length checks
]

[tool.ruff.lint.flake8-copyright]
author = "Canonical Ltd."
notice-rgx = "Copyright\\s\\d{4}([-,]\\d{4})*\\s+"

[tool.ruff.lint.mccabe]
max-complexity = 10

[tool.ruff.lint.pydocstyle]
convention = "google"
