# Copyright 2021 Canonical Ltd.
# See LICENSE file for licensing details.

[dependency-groups]
main = [
    "boto3~=1.28",
    "charmlibs-rollingops~=1.1",
    "jinja2~=3.1",
    "lightkube~=0.15.0",
    "ops[tracing]~=3.5",
    "pyyaml~=6.0",
    "tenacity~=8.2",
]
charm-libs = [
    # data_platform_libs/v0/data_interfaces.py
    "ops>=2.0.0",
    # data_platform_libs/v1/upgrade.py
    "poetry-core",
    # data_platform_libs/v1/upgrade.py
    # data_platform_libs/v1/data_models.py
    "pydantic~=2.0",
    # mysql/v0/*.py"
    "mysql_shell_client[contrib]~=1.0",
    # tls_certificates_interface/v1/tls_certificates.py
    # tls_certificates lib uses a feature only available in cryptography >=42.0.5
    "cryptography>=42.0.5",
    "jsonschema",
    # loki_k8s/v0/loki_push_api.py and prometheus_k8s/v0/prometheus_scrape.py
    "cosl>=1.10.3",
]
format = [
    "ruff~=0.12.7",
]
lint = [
    "ruff~=0.12.7",
    "codespell~=2.3",
    "shellcheck-py~=0.9.0",
]
unit = [
    "pytest~=9.0",
    "pytest-mock~=3.11",
    "coverage[toml]~=7.2",
    "parameterized~=0.9.0",
]
integration = [
    "pytest~=9.0",
    "jinja2~=3.1",
    "juju~=3.6",
    "mysql-connector-python~=26.7.0",
    "tenacity~=9.1",
    "boto3~=1.28",
    "pyyaml~=6.0",
    "urllib3~=2.0",
    "lightkube~=1.0.1",
    "allure-pytest~=2.13",
    "allure-pytest-default-results~=0.1.2",
    "jubilant-backports~=1.4",
]

[tool.poetry]
package-mode = false
requires-poetry = ">=2.2.0"

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.group.format]
optional = true

[tool.poetry.group.lint]
optional = true

[tool.coverage.run]
branch = true

[tool.coverage.report]
show_missing = true

[tool.pytest.ini_options]
minversion = "6.0"
log_cli_level = "INFO"
markers = ["juju3", "only_with_juju_secrets", "only_without_juju_secrets"]

# Linting tools configuration
[tool.ruff]
# preview and explicit preview are enabled for CPY001
preview = true
target-version = "py310"
src = ["src", "."]
line-length = 99

[tool.ruff.lint]
explicit-preview-rules = true
select = [
    "A",
    "E",
    "W",
    "F",
    "C",
    "N",
    "D",
    "I",
    "B",
    "CPY001",
    "RUF",
    "S",
    "SIM",
    "UP",
    "TC",
]
ignore = [
    "D107", # Ignore D107 Missing docstring in __init__
    "E501", # Ignore E501 Line too long
]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = [
    "D104", # Ignore D104 Missing docstring in __init__.py
    "F403", # Ignore F403 Unable to detect undefined names
]
"tests/*" = [
    "D1",
    "D417",
    # Asserts
    "B011",
    # Disable security checks for tests
    "S",
]

[tool.ruff.lint.flake8-copyright]
# Check for properly formatted copyright header in each file
author = "Canonical Ltd."
notice-rgx = "Copyright\\s\\d{4}([-,]\\d{4})*\\s+"

[tool.ruff.lint.mccabe]
max-complexity = 10

[tool.ruff.lint.pydocstyle]
convention = "google"
