# Copyright 2021 Canonical Ltd.
# See LICENSE file for licensing details.

[tox]
no_package = True
env_list = lint, unit

[vars]
src_path = "{tox_root}/src"
tests_path = "{tox_root}/tests"
scripts_path = "{tox_root}/scripts"
terraform_path = "{tox_root}/terraform"
all_path = {[vars]src_path} {[vars]tests_path} {[vars]scripts_path}

[testenv]
set_env =
    PYTHONPATH = {tox_root}/src:{tox_root}/lib
    PY_COLORS = 1

[testenv:format]
description = Apply coding style standards to code
skip_install = true
dependency_groups =
    format
commands =
    ruff check --fix {[vars]all_path}
    ruff format {[vars]all_path}

[testenv:lint]
description = Check code against coding style standards
skip_install = true
allowlist_externals =
    {[testenv]allowlist_externals}
    find
dependency_groups =
    lint
commands =
    codespell {[vars]all_path}
    ruff check {[vars]all_path}
    ruff format --check --diff {[vars]all_path}
    find {[vars]all_path} -type f \( -name "*.sh" -o -name "*.bash" \) -exec shellcheck --color=always \{\} +

[testenv:lint-terraform]
description = Check code against Terraform style standards
skip_install = true
allowlist_externals =
    {[testenv]allowlist_externals}
    terraform
commands =
    terraform fmt -check -diff -recursive {[vars]terraform_path}
    terraform -chdir={[vars]terraform_path} init -backend=false
    terraform -chdir={[vars]terraform_path} validate

[testenv:unit]
description = Run unit tests
dependency_groups =
    main
    charm-libs
    unit
commands =
    coverage run --source={[vars]src_path} \
        -m pytest -v --tb native -s {posargs} {[vars]tests_path}/unit
    coverage report
    coverage xml

[testenv:integration]
description = Run integration tests
pass_env =
    CI
    MYSQL_IMAGE
    CHARM_REVISION_AMD64
    CHARM_REVISION_ARM64
    AWS_ENDPOINT_URL
    AWS_ACCESS_KEY
    AWS_SECRET_KEY
    GCP_ACCESS_KEY
    GCP_SECRET_KEY
    CEPH_ENDPOINT_URL
    CEPH_ACCESS_KEY
    CEPH_SECRET_KEY
skip_install = true
dependency_groups =
    integration
commands =
    pytest -v -x --tb native --log-cli-level=INFO -s --ignore={[vars]tests_path}/unit/ {posargs}
