# Copyright 2025 Canonical Ltd.
# See LICENSE file for licensing details.
name: Automatic doc checks

on:
  push:
    branches:
      - '8.0/edge'
  pull_request:
    paths:
      - '/docs/**'
  workflow_dispatch:


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  documentation-checks:
    uses: canonical/documentation-workflows/.github/workflows/documentation-checks.yaml@main
    with:
      working-directory: "docs"
      fetch-depth: 0
