# Copyright 2025 Canonical Ltd.
# See LICENSE file for licensing details.
name: Automatic doc checks

on:
  push:
    branches:
      - '8.4/edge'
  pull_request:
    paths:
      - 'kubernetes/docs/**'
      - 'machines/docs/**'
  workflow_dispatch:


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  documentation-checks:
    strategy:
      matrix:
        path:
          - kubernetes
          - machines
    uses: canonical/documentation-workflows/.github/workflows/documentation-checks.yaml@main
    with:
      working-directory: ${{ matrix.path }}/docs
      fetch-depth: 0
