# Copyright 2025 Canonical Ltd.
# See LICENSE file for licensing details.
name: Check libs

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths-ignore:
      - 'kubernetes/.gitignore'
      - 'kubernetes/.jujuignore'
      - 'kubernetes/docs/**'
      - 'machines/.gitignore'
      - 'machines/.jujuignore'
      - 'machines/docs/**'
      - 'LICENSE'
      - '**.md'
      - '.github/renovate.json5'
      - '.github/workflows/*.yaml'

jobs:
  lib-check:
    name: Check libraries
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: ${{ github.event.pull_request.head.repo.full_name == 'canonical/mysql-operators' }}
    strategy:
      matrix:
        path:
          - kubernetes
          - machines
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Check libs
        uses: canonical/charming-actions/check-libraries@2.7.0
        with:
          charm-path: ${{ matrix.path }}
          credentials: "${{ secrets.CHARMHUB_TOKEN }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
