# Copyright 2023 Canonical Ltd.
# See LICENSE file for licensing details.
name: Release to Charmhub

on:
  push:
    branches:
      - '8.4/edge'
    paths-ignore:
      - 'docs/**'
      - '.github/renovate.json5'
      - '.github/workflows/*.yaml'

jobs:
  build:
    name: Build charm | ${{ matrix.path }}
    strategy:
      fail-fast: false
      matrix:
        path:
          - kubernetes
          - machines
    uses: canonical/data-platform-workflows/.github/workflows/build_charm.yaml@v42.0.1
    with:
      path-to-charm-directory: ${{ matrix.path }}

  integration-test:
    name: Integration tests
    needs:
      - build
    strategy:
      fail-fast: false
      matrix:
        path:
          - kubernetes
          - machines
    uses: ./.github/workflows/integration_test.yaml
    with:
      artifact-prefix: ${{ needs.build.outputs.artifact-prefix }}
      path-to-charm-directory: ${{ matrix.path }}
    secrets: inherit

# TODO: Uncomment when MySQL 8.4/stable channel has releases
#  release-test:
#    name: Release tests
#    needs:
#      - build
#    strategy:
#      fail-fast: false
#      matrix:
#        path:
#          - kubernetes
#          - machines
#    uses: ./.github/workflows/release_test.yaml
#    with:
#      artifact-prefix: ${{ needs.build.outputs.artifact-prefix }}
#      path-to-charm-directory: ${{ matrix.path }}
#    secrets: inherit

  release:
    name: Release charm | ${{ matrix.path }}
    needs:
      - build
      - integration-test
      # - release-test
    strategy:
      fail-fast: false
      matrix:
        path:
          - kubernetes
          - machines
    uses: canonical/data-platform-workflows/.github/workflows/release_charm_edge.yaml@v42.0.1
    with:
      track: '8.4'
      artifact-prefix: ${{ needs.build.outputs.artifact-prefix }}
      path-to-charm-directory: ${{ matrix.path }}
    secrets:
      charmhub-token: ${{ secrets.CHARMHUB_TOKEN }}
    permissions:
      contents: write  # Needed to create git tags
