# Copyright 2023 Canonical Ltd.
# See LICENSE file for licensing details.
name: Release to Charmhub

on:
  push:
    branches:
      - '8.0/edge'
    paths-ignore:
      - 'docs/**'
      - '.github/renovate.json5'
      - '.github/workflows/*.yaml'

jobs:
  build:
    name: Build charm | ${{ matrix.path }}
    strategy:
      fail-fast: false
      matrix:
        path:
          - kubernetes
          - machines
    uses: canonical/data-platform-workflows/.github/workflows/build_charm.yaml@v48.1.1
    with:
      path-to-charm-directory: ${{ matrix.path }}
    permissions:
      actions: read
      contents: read

  integration-test:
    name: Integration tests
    needs:
      - build
    strategy:
      fail-fast: false
      matrix:
        path:
          - kubernetes
          - machines
    uses: ./.github/workflows/integration_test.yaml
    with:
      artifact-prefix: ${{ needs.build.outputs.artifact-prefix }}
      path-to-charm-directory: ${{ matrix.path }}
    secrets: inherit
    permissions:
      actions: read

  release-test:
    name: Release tests
    needs:
      - build
    strategy:
      fail-fast: false
      matrix:
        path:
          - kubernetes
          - machines
    uses: ./.github/workflows/release_test.yaml
    with:
      artifact-prefix: ${{ needs.build.outputs.artifact-prefix }}
      path-to-charm-directory: ${{ matrix.path }}
    secrets: inherit
    permissions:
      actions: read

  release:
    name: Release charm | ${{ matrix.path }}
    needs:
      - build
      - integration-test
      - release-test
    strategy:
      fail-fast: false
      matrix:
        path:
          - kubernetes
          - machines
    uses: canonical/data-platform-workflows/.github/workflows/release_charm_edge.yaml@v48.1.1
    with:
      track: '8.0'
      artifact-prefix: ${{ needs.build.outputs.artifact-prefix }}
      path-to-charm-directory: ${{ matrix.path }}
    secrets:
      charmhub-token: ${{ secrets.CHARMHUB_TOKEN }}
    permissions:
      actions: read    # Needed for GitHub API call to get workflow version
      contents: write  # Needed to create git tags
