# Copyright 2026 Canonical Ltd.
# See LICENSE file for licensing details.

name: Temporary TICS scan

on:
  push:
    branches:
      - soundarya/temp-tiobe-trigger

jobs:
  TICS-k8s-80:
    name: TICS scan | mysql-k8s-80
    uses: ./.github/workflows/tiobe_scan.yaml
    with:
      operator: kubernetes
      ref: backport/e1f560051-to-8.0-edge
      project: mysql-k8s-8.0
    secrets: inherit
  TICS-vm-80:
    name: TICS scan | mysql-vm-80
    uses: ./.github/workflows/tiobe_scan.yaml
    with:
      operator: machines
      ref: backport/e1f560051-to-8.0-edge
      project: mysql-vm-8.0
    secrets: inherit
  TICS-k8s-84:
    name: TICS scan | mysql-k8s-84
    uses: ./.github/workflows/tiobe_scan.yaml
    with:
      operator: kubernetes
      ref: 8.4/edge
      project: mysql-k8s-8.4
    secrets: inherit
  TICS-vm-84:
    name: TICS scan | mysql-vm-84
    uses: ./.github/workflows/tiobe_scan.yaml
    with:
      operator: machines
      ref: 8.4/edge
      project: mysql-vm-8.4
    secrets: inherit
